#!/bin/bash

# =========================================
# SNIPE QUICK COMMANDS REFERENCE
# =========================================

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     SNIPE QUICK COMMANDS REFERENCE             ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${YELLOW}📱 DEVELOPMENT${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}Start Dev Server:${NC}"
echo "  cd Onchainweb && npm run dev"
echo ""
echo -e "${GREEN}Install Dependencies:${NC}"
echo "  cd Onchainweb && npm install"
echo ""
echo -e "${GREEN}Build for Production:${NC}"
echo "  cd Onchainweb && npm run build"
echo ""
echo -e "${GREEN}Preview Production Build:${NC}"
echo "  cd Onchainweb && npm run preview"
echo ""

echo -e "${YELLOW}🔐 FIREBASE${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}Deploy Firebase (Rules + Indexes):${NC}"
echo "  firebase deploy --only firestore:rules,firestore:indexes"
echo ""
echo -e "${GREEN}Deploy Everything:${NC}"
echo "  firebase deploy"
echo ""
echo -e "${GREEN}Check Firebase Status:${NC}"
echo "  firebase projects:list"
echo ""
echo -e "${GREEN}View Firestore Data:${NC}"
echo "  firebase firestore:list"
echo ""
echo -e "${GREEN}Run Firebase Setup Script:${NC}"
echo "  ./firebase-setup.sh"
echo ""

echo -e "${YELLOW}👤 ADMIN SETUP${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}Master Account:${NC}"
echo "  Email: master@gmail.com"
echo "  Password: (create in Firebase Console)"
echo "  Login: http://localhost:5173/master-admin"
echo ""
echo -e "${GREEN}Create Master (Firebase Console):${NC}"
echo "  1. Go to console.firebase.google.com"
echo "  2. Select: YOUR_FIREBASE_PROJECT_ID"
echo "  3. Click: Authentication > + Create user"
echo "  4. Email: master@gmail.com"
echo "  5. Password: (strong password)"
echo ""

echo -e "${YELLOW}🌐 ENVIRONMENT${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}Frontend .env Location:${NC}"
echo "  Onchainweb/.env"
echo ""
echo -e "${GREEN}Required Variables:${NC}"
echo "  ✅ VITE_FIREBASE_API_KEY"
echo "  ✅ VITE_FIREBASE_AUTH_DOMAIN"
echo "  ✅ VITE_FIREBASE_PROJECT_ID"
echo "  ✅ VITE_FIREBASE_STORAGE_BUCKET"
echo "  ✅ VITE_FIREBASE_MESSAGING_SENDER_ID"
echo "  ✅ VITE_FIREBASE_APP_ID"
echo "  ✅ VITE_FIREBASE_MEASUREMENT_ID"
echo "  ✅ VITE_WALLETCONNECT_PROJECT_ID"
echo "  ✅ VITE_ENABLE_ADMIN=true"
echo "  ✅ VITE_ADMIN_ALLOWLIST=..."
echo ""

echo -e "${YELLOW}🧪 TESTING${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}Check API Health:${NC}"
echo "  curl https://snipe-api.onrender.com/api/health"
echo ""
echo -e "${GREEN}Test Master Login:${NC}"
echo "  1. Start: npm run dev"
echo "  2. Visit: http://localhost:5173/master-admin"
echo "  3. Username: master"
echo "  4. Password: (from Firebase)"
echo ""
echo -e "${GREEN}Test User Provisioning:${NC}"
echo "  1. Visit: http://localhost:5173"
echo "  2. Connect Wallet"
echo "  3. Check localStorage: registeredUsers"
echo ""

echo -e "${YELLOW}📊 MONITORING${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}Firebase Console:${NC}"
echo "  https://console.firebase.google.com"
echo ""
echo -e "${GREEN}Developer Console (Browser):${NC}"
echo "  Press: F12 or Right-click > Inspect"
echo "  Look for: [LOGIN] [PROVISIONING] [FIREBASE] logs"
echo ""
echo -e "${GREEN}Network Tab:${NC}"
echo "  Check Firestore requests"
echo "  Monitor response times"
echo ""

echo -e "${YELLOW}🚀 DEPLOYMENT${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}Deploy to Vercel:${NC}"
echo "  npm install -g vercel"
echo "  vercel"
echo ""
echo -e "${GREEN}Deploy to Firebase Hosting:${NC}"
echo "  firebase deploy --only hosting"
echo ""
echo -e "${GREEN}Deploy Everything:${NC}"
echo "  firebase deploy"
echo ""

echo -e "${YELLOW}📚 DOCUMENTATION${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}Setup Guides:${NC}"
echo "  - SETUP_COMPLETE_SUMMARY.md (this guide)"
echo "  - FIREBASE_SETUP_COMPLETE.md"
echo "  - FIREBASE_EXTENSIONS_SETUP.md"
echo "  - FIREBASE_AUTO_PROVISIONING.md"
echo "  - QUICK_START_GUIDE.md"
echo ""

echo -e "${YELLOW}💻 PROJECT STRUCTURE${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}Frontend:${NC}"
echo "  Onchainweb/"
echo "    ├─ src/"
echo "    ├─ public/"
echo "    ├─ .env (configuration)"
echo "    └─ package.json"
echo ""
echo -e "${GREEN}Firebase:${NC}"
echo "  ├─ firebase.json"
echo "  ├─ firestore.rules"
echo "  ├─ firestore.indexes.json"
echo "  ├─ .firebaserc"
echo "  └─ firebase-setup.sh"
echo ""
echo -e "${GREEN}Backend (Express):${NC}"
echo "  backend/"
echo "    ├─ index.js"
echo "    ├─ routes/"
echo "    ├─ models/"
echo "    └─ package.json (deprecated)"
echo ""

echo -e "${BLUE}╔════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  Ready to start? Run: cd Onchainweb && npm run dev    ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════╝${NC}"
echo ""
